version: '3.4'

services:
  blazordemo.api:
    image: ${DOCKER_REGISTRY-}blazordemoapi
    build:
      context: .
      dockerfile: BlazorDemo.Api/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672